### ISSUE TITLE
Lijst van dingen vertaling

### ISSUE THREAD

**Issue by christiaanwesterbeek** [pimschaaf/ra-language-dutch#3]
De vertaling van `page.list: '%{name} lijst'` levert onjuiste teksten op omdat samengestelde woorden (itt in het engels) aanelkaar geschreven moeten worden.
- boeken lijst
- dingen lijst
- leerlingen lijst

Zouden eigenlijk moeten zijn:
- Lijst van boeken of boekenlijst
- Lijst van dingen (dingenlijst is een beetje raar)
- Lijst van leerlingen of leerlingenlijst 

Ik stel voor om de definitie aan te passen naar:

`page.list: 'Lijst van %{name}'`

**Comment by pimschaaf** [comment]
@christiaanwesterbeek Goede idee. Ik ben het met je eens dat `%{name} lijst` onjuiste teksten geeft.

Ik voel persoonlijk juist meer voor `%{name}lijst` als ik je voorbeelden lees.

`%{name}` is hier over het algemeen enkelvoud toch? Dus dan wordt het als ik mij niet vergis:

- Boeklijst of Lijst van boek
- Dinglijst of Lijst van ding
- Leerlinglijst of Lijst van leerling

Ik vind dan in de meeste gevallen de `%{name}lijst` beter (alhoewel een meervoud voor `lijst` vaak nog mooier zou zijn). Dit gaat volgens mij ook eigenlijk altijd goed, bijvoorbeeld in samenstellingen zoals:

- Cafélijst
- Schoollijst

en een serie zoals onder Hyponiemen op https://nl.wiktionary.org/wiki/lijst

Ik ben benieuwd of jij je ook kan vinden in de keus voor `%{name}lijst`. Ik laat dit issue sowieso nog even (laat zeggen een week) open om (anderen) ruimte te geven voor eventuele andere inzichten.

**Comment by christiaanwesterbeek** [comment]
In `%{name}lijst` kan ik me ook vinden. dingenlijst was toch al een beetje gezocht. Of %name meervoud is hangt af van wat als resource name gekozen is. Vaak is die meervoud zoals [hier](https://github.com/marmelab/react-admin/blob/master/docs/List.md#the-list-component) Posts [aansluitend op de rest interface](https://github.com/marmelab/react-admin/issues/415#issuecomment-285631748).

React-admin probeert daar nog het meervoud van te maken: https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/ListController.js#L255-L261 en neemt daarmee net wat staat na de |||| in de [resource name vertalingen](https://github.com/marmelab/react-admin/blob/master/docs/Translation.md#translating-resource-and-field-names).

**Comment by pimschaaf** [comment]
Oké perfect. Dan maak ik het begin volgende week `%{name}lijst`.

**Comment by pimschaaf** [comment]
Toegevoegd in [patch 2.0.1](https://github.com/pimschaaf/ra-language-dutch/releases/tag/v2.0.1).
